package entities;

// default package
// Generated 2016-mar-22 19:24:14 by Hibernate Tools 4.3.1.Final

/**
 * Airport generated by hbm2java
 */
public class Airport extends AbstractEntity<String> implements java.io.Serializable {

	private String airportId;
	private String airportCity;

	public Airport() {
	}

	public Airport(String airportId) {
		this.airportId = airportId;
	}

	public Airport(String airportId, String airportCity) {
		this.airportId = airportId;
		this.airportCity = airportCity;
	}

	public String getAirportId() {
		return this.airportId;
	}

	public void setAirportId(String airportId) {
		this.airportId = airportId;
	}

	public String getAirportCity() {
		return this.airportCity;
	}

	public void setAirportCity(String airportCity) {
		this.airportCity = airportCity;
	}

	@Override
	public String getKey() {
		return airportId;
	}

	@Override
	public void setKey(String key) {
		airportId = key;
	}
}
