package entities;

// default package
// Generated 2016-mar-22 19:24:14 by Hibernate Tools 4.3.1.Final

/**
 * BookingId generated by hbm2java
 */
public class BookingId implements java.io.Serializable {

	private String flightId;
	private String passenger;
	private String date;

	public BookingId() {
	}

	public BookingId(String flightId, String passenger, String date) {
		this.flightId = flightId;
		this.passenger = passenger;
		this.date = date;
	}

	public String getFlightId() {
		return this.flightId;
	}

	public void setFlightId(String flightId) {
		this.flightId = flightId;
	}

	public String getPassenger() {
		return this.passenger;
	}

	public void setPassenger(String passenger) {
		this.passenger = passenger;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BookingId))
			return false;
		BookingId castOther = (BookingId) other;

		return ((this.getFlightId() == castOther.getFlightId()) || (this.getFlightId() != null
				&& castOther.getFlightId() != null && this.getFlightId().equals(castOther.getFlightId())))
				&& ((this.getPassenger() == castOther.getPassenger()) || (this.getPassenger() != null
						&& castOther.getPassenger() != null && this.getPassenger().equals(castOther.getPassenger())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFlightId() == null ? 0 : this.getFlightId().hashCode());
		result = 37 * result + (getPassenger() == null ? 0 : this.getPassenger().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
