package entities;

// default package
// Generated 2016-apr-01 17:41:47 by Hibernate Tools 4.3.1.Final

/**
 * Flight generated by hbm2java
 */
public class Flight extends AbstractEntity<FlightId> implements java.io.Serializable {

	private FlightId id;
	private String departureTime;
	private String duration;
	private int capacity;
	private int freeSeats;
	private String origin;
	private String destination;
	private String price;
	private String promotion;

	public Flight() {
	}

	public Flight(FlightId id, String departureTime, int capacity, int freeSeats, String origin, String destination) {
		this.id = id;
		this.departureTime = departureTime;
		this.capacity = capacity;
		this.freeSeats = freeSeats;
		this.origin = origin;
		this.destination = destination;
	}

	public Flight(FlightId id, String departureTime, String duration, int capacity, int freeSeats, String origin,
			String destination, String price, String promotion) {
		this.id = id;
		this.departureTime = departureTime;
		this.duration = duration;
		this.capacity = capacity;
		this.freeSeats = freeSeats;
		this.origin = origin;
		this.destination = destination;
		this.price = price;
		this.promotion = promotion;
	}

	public FlightId getId() {
		return this.id;
	}

	public void setId(FlightId id) {
		this.id = id;
	}

	public String getDepartureTime() {
		return this.departureTime;
	}

	public void setDepartureTime(String departureTime) {
		this.departureTime = departureTime;
	}

	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public int getCapacity() {
		return this.capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	public int getFreeSeats() {
		return this.freeSeats;
	}

	public void setFreeSeats(int freeSeats) {
		this.freeSeats = freeSeats;
	}

	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getPromotion() {
		return this.promotion;
	}

	public void setPromotion(String promotion) {
		this.promotion = promotion;
	}

	@Override
	public FlightId getKey() {
		return id;
	}

	@Override
	public void setKey(FlightId key) {
		this.id = key;
		
	}

	@Override
	public String toString() {
		return  departureTime + " | " + origin + " | " + duration + " | " + destination + " | " + price + " SGD";
	}
}
