package entities;

// default package
// Generated 2016-apr-01 17:41:47 by Hibernate Tools 4.3.1.Final

/**
 * FlightId generated by hbm2java
 */
public class FlightId implements java.io.Serializable {

	private String flightId;
	private String date;

	public FlightId() {
	}

	public FlightId(String flightId, String date) {
		this.flightId = flightId;
		this.date = date;
	}

	public String getFlightId() {
		return this.flightId;
	}

	public void setFlightId(String flightId) {
		this.flightId = flightId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}
	
	

	@Override
	public String toString() {
		return flightId + " | " + date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FlightId))
			return false;
		FlightId castOther = (FlightId) other;

		return ((this.getFlightId() == castOther.getFlightId()) || (this.getFlightId() != null
				&& castOther.getFlightId() != null && this.getFlightId().equals(castOther.getFlightId())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFlightId() == null ? 0 : this.getFlightId().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
