package entities;

// default package
// Generated 2016-mar-28 14:16:35 by Hibernate Tools 4.3.1.Final

/**
 * Mybookingselement generated by hbm2java
 */
public class Mybookingselement extends AbstractEntity<MybookingselementId> implements java.io.Serializable {

	private MybookingselementId id;

	public Mybookingselement() {
	}

	public Mybookingselement(MybookingselementId id) {
		this.id = id;
	}

	public MybookingselementId getId() {
		return this.id;
	}

	public void setId(MybookingselementId id) {
		this.id = id;
	}

	@Override
	public MybookingselementId getKey() {
		return id;
	}

	@Override
	public void setKey(MybookingselementId key) {
		this.id = key;
		
	}

	@Override
	public String toString() {
		return id.getFlightId() + " | " + id.getDate() + " - " + id.getDepartureTime() + " | " + id.getOrigin() + " | " + id.getDuration() + " | " + id.getDestination();
	}
	
	

}
