package entities;

// default package
// Generated 2016-mar-28 14:16:35 by Hibernate Tools 4.3.1.Final

/**
 * MybookingselementId generated by hbm2java
 */
public class MybookingselementId implements java.io.Serializable {

	private String flightId;
	private String date;
	private String departureTime;
	private String duration;
	private String origin;
	private String destination;
	private String firstname;
	private String lastname;
	private String passportNr;
	private String user;

	public MybookingselementId() {
	}

	public MybookingselementId(String flightId, String date, String departureTime, String origin, String destination,
			String firstname, String lastname, String passportNr) {
		this.flightId = flightId;
		this.date = date;
		this.departureTime = departureTime;
		this.origin = origin;
		this.destination = destination;
		this.firstname = firstname;
		this.lastname = lastname;
		this.passportNr = passportNr;
	}

	public MybookingselementId(String flightId, String date, String departureTime, String duration, String origin,
			String destination, String firstname, String lastname, String passportNr, String user) {
		this.flightId = flightId;
		this.date = date;
		this.departureTime = departureTime;
		this.duration = duration;
		this.origin = origin;
		this.destination = destination;
		this.firstname = firstname;
		this.lastname = lastname;
		this.passportNr = passportNr;
		this.user = user;
	}

	public String getFlightId() {
		return this.flightId;
	}

	public void setFlightId(String flightId) {
		this.flightId = flightId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getDepartureTime() {
		return this.departureTime;
	}

	public void setDepartureTime(String departureTime) {
		this.departureTime = departureTime;
	}

	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getPassportNr() {
		return this.passportNr;
	}

	public void setPassportNr(String passportNr) {
		this.passportNr = passportNr;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MybookingselementId))
			return false;
		MybookingselementId castOther = (MybookingselementId) other;

		return ((this.getFlightId() == castOther.getFlightId()) || (this.getFlightId() != null
				&& castOther.getFlightId() != null && this.getFlightId().equals(castOther.getFlightId())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())))
				&& ((this.getDepartureTime() == castOther.getDepartureTime())
						|| (this.getDepartureTime() != null && castOther.getDepartureTime() != null
								&& this.getDepartureTime().equals(castOther.getDepartureTime())))
				&& ((this.getDuration() == castOther.getDuration()) || (this.getDuration() != null
						&& castOther.getDuration() != null && this.getDuration().equals(castOther.getDuration())))
				&& ((this.getOrigin() == castOther.getOrigin()) || (this.getOrigin() != null
						&& castOther.getOrigin() != null && this.getOrigin().equals(castOther.getOrigin())))
				&& ((this.getDestination() == castOther.getDestination())
						|| (this.getDestination() != null && castOther.getDestination() != null
								&& this.getDestination().equals(castOther.getDestination())))
				&& ((this.getFirstname() == castOther.getFirstname()) || (this.getFirstname() != null
						&& castOther.getFirstname() != null && this.getFirstname().equals(castOther.getFirstname())))
				&& ((this.getLastname() == castOther.getLastname()) || (this.getLastname() != null
						&& castOther.getLastname() != null && this.getLastname().equals(castOther.getLastname())))
				&& ((this.getPassportNr() == castOther.getPassportNr()) || (this.getPassportNr() != null
						&& castOther.getPassportNr() != null && this.getPassportNr().equals(castOther.getPassportNr())))
				&& ((this.getUser() == castOther.getUser()) || (this.getUser() != null && castOther.getUser() != null
						&& this.getUser().equals(castOther.getUser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFlightId() == null ? 0 : this.getFlightId().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getDepartureTime() == null ? 0 : this.getDepartureTime().hashCode());
		result = 37 * result + (getDuration() == null ? 0 : this.getDuration().hashCode());
		result = 37 * result + (getOrigin() == null ? 0 : this.getOrigin().hashCode());
		result = 37 * result + (getDestination() == null ? 0 : this.getDestination().hashCode());
		result = 37 * result + (getFirstname() == null ? 0 : this.getFirstname().hashCode());
		result = 37 * result + (getLastname() == null ? 0 : this.getLastname().hashCode());
		result = 37 * result + (getPassportNr() == null ? 0 : this.getPassportNr().hashCode());
		result = 37 * result + (getUser() == null ? 0 : this.getUser().hashCode());
		return result;
	}

}
