package entities;

// default package
// Generated 2016-apr-03 17:18:57 by Hibernate Tools 4.3.1.Final

/**
 * PromotionId generated by hbm2java
 */
public class PromotionId implements java.io.Serializable {

	private String originCity;
	private String originId;
	private String destinationId;
	private String destinationCity;
	private String price;

	public PromotionId() {
	}

	public PromotionId(String originId, String destinationId) {
		this.originId = originId;
		this.destinationId = destinationId;
	}

	public PromotionId(String originCity, String originId, String destinationId, String destinationCity, String price) {
		this.originCity = originCity;
		this.originId = originId;
		this.destinationId = destinationId;
		this.destinationCity = destinationCity;
		this.price = price;
	}

	public String getOriginCity() {
		return this.originCity;
	}

	public void setOriginCity(String originCity) {
		this.originCity = originCity;
	}

	public String getOriginId() {
		return this.originId;
	}

	public void setOriginId(String originId) {
		this.originId = originId;
	}

	public String getDestinationId() {
		return this.destinationId;
	}

	public void setDestinationId(String destinationId) {
		this.destinationId = destinationId;
	}

	public String getDestinationCity() {
		return this.destinationCity;
	}

	public void setDestinationCity(String destinationCity) {
		this.destinationCity = destinationCity;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PromotionId))
			return false;
		PromotionId castOther = (PromotionId) other;

		return ((this.getOriginCity() == castOther.getOriginCity()) || (this.getOriginCity() != null
				&& castOther.getOriginCity() != null && this.getOriginCity().equals(castOther.getOriginCity())))
				&& ((this.getOriginId() == castOther.getOriginId()) || (this.getOriginId() != null
						&& castOther.getOriginId() != null && this.getOriginId().equals(castOther.getOriginId())))
				&& ((this.getDestinationId() == castOther.getDestinationId())
						|| (this.getDestinationId() != null && castOther.getDestinationId() != null
								&& this.getDestinationId().equals(castOther.getDestinationId())))
				&& ((this.getDestinationCity() == castOther.getDestinationCity())
						|| (this.getDestinationCity() != null && castOther.getDestinationCity() != null
								&& this.getDestinationCity().equals(castOther.getDestinationCity())))
				&& ((this.getPrice() == castOther.getPrice()) || (this.getPrice() != null
						&& castOther.getPrice() != null && this.getPrice().equals(castOther.getPrice())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOriginCity() == null ? 0 : this.getOriginCity().hashCode());
		result = 37 * result + (getOriginId() == null ? 0 : this.getOriginId().hashCode());
		result = 37 * result + (getDestinationId() == null ? 0 : this.getDestinationId().hashCode());
		result = 37 * result + (getDestinationCity() == null ? 0 : this.getDestinationCity().hashCode());
		result = 37 * result + (getPrice() == null ? 0 : this.getPrice().hashCode());
		return result;
	}

}
