package entities;

// default package
// Generated 2016-apr-03 17:18:57 by Hibernate Tools 4.3.1.Final

/**
 * Promotion generated by hbm2java
 */
public class Promotion extends AbstractEntity<PromotionId> implements java.io.Serializable {

	private PromotionId id;

	public Promotion() {
	}

	public Promotion(PromotionId id) {
		this.id = id;
	}

	public PromotionId getId() {
		return this.id;
	}

	public void setId(PromotionId id) {
		this.id = id;
	}

	@Override
	public PromotionId getKey() {
		return id;
	}

	@Override
	public void setKey(PromotionId key) {
		this.id = key;
	}

	@Override
	public String toString() {
		return "Route: " + id.getOriginCity() + " -> " + id.getDestinationCity() + " | Lowest available price: " + id.getPrice() + " SGD";
	}
	
	

}
