package entities;

// default package
// Generated 2016-mar-22 19:24:14 by Hibernate Tools 4.3.1.Final

/**
 * User generated by hbm2java
 */
public class User extends AbstractEntity<String> implements java.io.Serializable {

	private String username;
	private String password;
	private String email;
	private String admin;

	public User() {
	}

	public User(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public User(String username, String password, String email, String admin) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.admin = admin;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAdmin() {
		return this.admin;
	}

	public void setAdmin(String admin) {
		this.admin = admin;
	}

	@Override
	public String getKey() {
		return username;
	}

	@Override
	public void setKey(String key) {
		username = key;
		
	}

	@Override
	public String toString() {
		return username + " | " + email;
	}
	
	

}
